services:
  redis:
    image: redis
    networks:
      - devops-exercise
  backend:
    image: back
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - devops-exercise
    environment:
      - REDIS_SERVER=redis:6379
  frontend:
    image: front
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - devops-exercise
    environment:
      - BACKEND_API_URL=http://backend:4000
      - CLIENT_API_URL=http://backend:4000

#volumes:
#  db-data:
#    driver: flocker
#    driver_opts:
#      size: "10GiB"
    
networks:
  devops-exercise: {}